version: "3.9"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rust-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    environment:
      - RUST_LOG=info

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: leptos-frontend
    ports:
      - "3000:8080"
    depends_on:
      - backend
    environment:
      - LEPTOS_OUTPUT_NAME=rust-spfresh-frontend
  #   ports:
  #     - "3001:3000"
  #   environment:
  #     - BACKEND_URL=http://backend:8000
  #   depends_on:
  #     - backend
